services:
  telegram-bot-api:
    build: .
    container_name: telegram-bot-api
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    command: --local -p 8081 -s 8082

volumes:
  telegram-bot-api-data:
